image = "/capstor/store/cscs/swissai/a122/container_images2/enroot/aurora_arm64_modulus2404.new.new.sqsh"

writable = true
mounts = ["/users", "/capstor", "/iopsstor",
   ]

[annotations] 
com.hooks.aws_ofi_nccl.enabled = "true" 
com.hooks.aws_ofi_nccl.variant = "cuda12"

[env]
FI_CXI_DISABLE_HOST_REGISTER = "1"
FI_MR_CACHE_MONITOR = "userfaultfd"


